name: Data Issue
description: Report incorrect quest, item, or game data
title: "[Data]: "
labels: ["upstream"]
body:
  - type: markdown
    attributes:
      value: |
        **Note:** Quest and item data issues should be reported in the [data-overlay repository](https://github.com/TarkovTracker/tarkovdata).

        Only use this template if the data source is correct but our tracker isn't displaying or handling it properly. Otherwise, please report at the data-overlay repo.

        Thanks for reporting a data issue! Please provide specific details about the incorrect data.

  - type: dropdown
    id: data-type
    attributes:
      label: Data Type
      description: What type of data is incorrect?
      options:
        - Quest/Task
        - Item
        - Hideout Module
        - Trader
        - Map
        - Other
    validations:
      required: true

  - type: input
    id: item-name
    attributes:
      label: Quest/Item Name
      description: What is the name of the quest, item, or entity with incorrect data?
      placeholder: e.g., "Chemical - Part 4", "Secure Flash Drive"
    validations:
      required: true

  - type: textarea
    id: incorrect
    attributes:
      label: What is Incorrect?
      description: Describe what data is wrong.
      placeholder: |
        The quest shows it requires level 15 but it actually requires level 12.
        The objective count is wrong.
        The item image is incorrect.
    validations:
      required: true

  - type: textarea
    id: correct
    attributes:
      label: What is Correct?
      description: What should the correct data be?
      placeholder: The correct requirement is...
    validations:
      required: true

  - type: input
    id: source
    attributes:
      label: Source
      description: Where did you verify this information? (Wiki link, in-game screenshot, etc.)
      placeholder: https://escapefromtarkov.fandom.com/wiki/...
    validations:
      required: false

  - type: dropdown
    id: game-mode
    attributes:
      label: Game Mode
      description: Which game mode is affected?
      options:
        - PvP
        - PvE
        - Both
        - Not Applicable
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Proof
      description: Add screenshots or other proof of the correct data.
      placeholder: Drag and drop images here or paste URLs
    validations:
      required: false

  - type: input
    id: discord
    attributes:
      label: Discord Handle (Optional)
      description: Your Discord username if you'd like us to follow up
      placeholder: username#1234
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information.
    validations:
      required: false
